# Generated by Django 4.1.2 on 2022-10-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prodacts',
            new_name='Prodact',
        ),
    ]
