# Generated by Django 4.1.2 on 2022-10-10 16:15

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_prodacts_prodact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='prodact',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='prodact',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prodact',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
