# Generated by Django 4.1.2 on 2022-10-10 16:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_booking_remove_prodact_uuid_alter_prodact_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodact',
            name='id',
        ),
        migrations.AddField(
            model_name='prodact',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
