# Generated by Django 4.1.2 on 2022-10-10 16:34

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_prodact_id_prodact_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d')),
            ],
        ),
        migrations.DeleteModel(
            name='Prodact',
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default=115551, max_length=40),
            preserve_default=False,
        ),
    ]
