# Generated by Django 4.1.2 on 2022-10-10 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_article_delete_prodact_booking_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Prodact',
        ),
    ]
