# Generated by Django 4.1.2 on 2022-10-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_booking_name_booking_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodact',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
