# Generated by Django 4.1.2 on 2022-10-11 15:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_booking_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('new_category', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='prodact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.prodact'),
        ),
        migrations.AddField(
            model_name='prodact',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.category'),
        ),
    ]
