# Generated by Django 4.1.2 on 2022-10-11 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_category_alter_booking_prodact_prodact_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodact',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.category'),
        ),
    ]
