# Generated by Django 4.1.2 on 2022-10-11 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_prodact_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodact',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.category'),
        ),
    ]
