# Generated by Django 4.1.2 on 2022-10-12 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_prodact_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='prodact',
        ),
        migrations.AddField(
            model_name='prodact',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.booking'),
        ),
        migrations.AlterField(
            model_name='prodact',
            name='image',
            field=models.ImageField(upload_to='%y/%m/%d'),
        ),
    ]
