# Generated by Django 4.1.2 on 2022-10-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_remove_booking_prodact_prodact_booking_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Guest',
        ),
        migrations.RemoveField(
            model_name='prodact',
            name='booking',
        ),
    ]
