# Generated by Django 4.1.2 on 2022-10-13 13:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_rename_booking_guest_remove_prodact_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.guest')),
                ('prodact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.prodact')),
            ],
        ),
    ]
