# Generated by Django 4.1.2 on 2022-10-14 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_booking_slug_category_slug_guest_slug_prodact_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('new_category', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='prodact',
            name='slug',
        ),
    ]
