# Generated by Django 4.1.2 on 2022-10-14 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_guests_rename_a_categoryrr_product_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodact',
            name='category',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='Prodact',
        ),
    ]
