# Generated by Django 4.1.2 on 2022-10-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_remove_prodact_category_delete_booking_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Booking',
        ),
        migrations.RenameModel(
            old_name='Categoryrr',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Guests',
            new_name='Guest',
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
