# Generated by Django 4.1.2 on 2022-10-14 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_rename_book_booking_rename_categoryrr_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='prodact',
            new_name='product',
        ),
    ]
