# Generated by Django 4.1.2 on 2022-10-14 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_alter_booking_guest_delete_guest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guests',
            new_name='Guest',
        ),
    ]
